### ISSUE TITLE
Upload image, video, file

### ISSUE THREAD

**Issue by Carl-Johnsons** [Carl-Johnsons/Chat-Application#73]
- [x] Upload Image (4h)
- [x] Upload video (4h)
- [x] Upload file (8h)

**Comment by Carl-Johnsons** [comment]
```git
git checkout -b "feature-upload"
````

**Comment by Carl-Johnsons** [comment]
Create migration for upload persistence upload image, video, file
- [ ] Create table **File** {
      **Id** (GUID, PK)
      **PublicId** (string)
      **Name** (string ,max(200))
      **ExtensionTypeId** (GUID, Foreign key)
      **Size** (real) vd: 1MB => 1024 * 1024 byte (quy về byte)
      **Url**: (string)
} 

- [ ] Create Table ExtensionType{
      **Id** (GUID, PK)
      **Code** (string) vd: .exe => EXE
      **Value** (string) vd: .exe,
      **Type**: (string) vd:  (VIDEO, IMAGE, RAW)
} 

est: 8h

**Comment by lebathinh2003** [comment]
finished
